export const GET_COMENT = "GET_COMENT";
export const POST_COMENT = "POST_COMENT";
export const POST_COMENT_ON_COMENT = "POST_COMENT_ON_COMENT";
export const POST_COMENT_PROFESOR = "POST_COMENT_PROFESOR";
export const EDITAR_COMENT = "EDITAR_COMENT";
export const DELETE_COMENT = "DELETE_COMENT";