export const GET_NOTIFICACIONES = "GET_NOTIFICACIONES";
export const GET_NOTIFICACION = "GET_NOTIFICACION";
export const POST_NOTIFICACION = "POST_NOTIFICACION";
export const EDITAR_NOTIFICACION = "EDITAR_NOTIFICAION";
export const EDITAR_NOTIFICACIONES = "EDITAR_NOTIFICACIONES";
export const DELETE_NOTIFICACION = "DELETE_NOTIFICACION";