export const GET_PROFESORES = "GET_PROFESORES";
export const GET_PROFESOR_ID = "GET_PROFESOR_ID";
export const PUT_PROFESORES = "PUT_PROFESORES";
export const DELETE_PROFESORES = "DELETE_PROFESORES";
export const POST_PROFESORES = "POST_PROFESORES";
export const FILTER_PRECIO = "FILTER_PRECIO";
export const FILTER_PUNTUACION = "FILTER_PUNTUACION";
export const VACIAR_ESTADO = "VACIAR_ESTADO";
export const SET_PROFE_FILTERED = "SET_PROFE_FILTERED";
export const SORT_PRICE_BACK = "SORT_PRICE_BACK";
export const FILTER_PROF_COUNTRY_BACK = "FILTER_PROF_COUNTRY_BACK";
export const SORT_USER_BACK = "SORT_USER_BACK";

